spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  flyway:
    enabled: true
management:
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: 
        - refresh
        - metrics
logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
