spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  flyway:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: refresh
